apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hrtsrs3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hrtsrs3
  template:
    metadata:
      labels:
        app: hrtsrs3
    spec:
      containers:
      - image: okteto.dev/hrtsrs3:latest
        name: hrtsrs3
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "34a5d701-0a62-484b-9c12-644514adecf8"
        - name: Vless_Path
          value: "/gtued3"
        - name: Vmess_UUID
          value: "b5304379-ab1b-4050-9a26-c581a3381eee"
        - name: Vmess_Path
          value: "/tudjtdy3"
        - name: Share_Path
          value: "/ytydu3"
