apiVersion: apps/v1
kind: Deployment
metadata:
  name:  vsvfd4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vsvfd4
  template:
    metadata:
      labels:
        app: vsvfd4
    spec:
      containers:
      - image: okteto.dev/vsvfd4:latest
        name: vsvfd4
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "d05fccf7-8cc7-4bc2-b70a-692a89aa6178"
        - name: Vless_Path
          value: "/vnfids4"
        - name: Vmess_UUID
          value: "366d20c5-2416-490f-be8b-d62dd2bb5975"
        - name: Vmess_Path
          value: "/mvsde4"
        - name: Share_Path
          value: "/bhuj4"
