apiVersion: apps/v1
kind: Deployment
metadata:
  name:  bfgb3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bfgb3
  template:
    metadata:
      labels:
        app: bfgb3
    spec:
      containers:
      - image: okteto.dev/bfgb3:latest
        name: bfgb3
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "1b11b337-c6ec-4af7-a59d-fdc9e80e7fc1"
        - name: Vless_Path
          value: "/gvsa3"
        - name: Vmess_UUID
          value: "9b5ecb45-8cb7-4e0e-890a-e44f47006e11"
        - name: Vmess_Path
          value: "/vdfbmm"
        - name: Share_Path
          value: "/vfdsv3"
