apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ertytrer3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ertytrer3
  template:
    metadata:
      labels:
        app: ertytrer3
    spec:
      containers:
      - image: okteto.dev/ertytrer3:latest
        name: ertytrer3
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "1d980dd1-00dd-49b7-a9f4-a14f6c717fd5"
        - name: Vless_Path
          value: "/gthsa3"
        - name: Vmess_UUID
          value: "01e7f1f0-bdc3-4fd5-bb84-d3ad1e90d84e"
        - name: Vmess_Path
          value: "/bdfbmm"
        - name: Share_Path
          value: "/vfdsv3"
