apiVersion: apps/v1
kind: Deployment
metadata:
  name:  vqevef2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vqevef2
  template:
    metadata:
      labels:
        app: vqevef2
    spec:
      containers:
      - image: okteto.dev/vqevef2:latest
        name: vqevef2
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "3731a1ad-4ff0-4e98-ad22-b9764062d2fb"
        - name: Vless_Path
          value: "/bebsd2"
        - name: Vmess_UUID
          value: "5157bb23-4701-4744-ae0a-704c9ae2b760"
        - name: Vmess_Path
          value: "/mfddjl2"
        - name: Share_Path
          value: "/hghj3"
