apiVersion: apps/v1
kind: Deployment
metadata:
  name:  qfger5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qfger5
  template:
    metadata:
      labels:
        app: qfger5
    spec:
      containers:
      - image: okteto.dev/qfger5:latest
        name: qfger5
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "088d29f7-6793-490f-87bf-ea82996101a6"
        - name: Vless_Path
          value: "/cdsavds5"
        - name: Vmess_UUID
          value: "38d1900b-e33a-42fa-81fc-ea504126d33d"
        - name: Vmess_Path
          value: "/mvsavd5"
        - name: Share_Path
          value: "/vafbdfew5"
