apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nbckxj2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nbckxj2
  template:
    metadata:
      labels:
        app: nbckxj2
    spec:
      containers:
      - image: okteto.dev/nbckxj2:latest
        name: nbckxj2
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "4cb4e94c-53db-49bf-80e5-c8d23ed0f57d"
        - name: Vless_Path
          value: "/uiok"
        - name: Vmess_UUID
          value: "b6ae6891-ba72-4866-982d-1775f38616e0"
        - name: Vmess_Path
          value: "/ioh"
        - name: Share_Path
          value: "/hghjkh"
