apiVersion: v1
kind: Service
metadata:
  name: hrtsrs3
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "hrtsrs3"
    port: 8080
  selector:
    app: hrtsrs3
