apiVersion: v1
kind: Service
metadata:
  name: vsvfd4
  annotations:
    dev.okteto.com/auto-ingress: "vsvfd4"
spec:
  type: ClusterIP  
  ports:
  - name: "nbckxj2"
    port: 8080
  selector:
    app: vsvfd4
